### ISSUE TITLE
Brackets-Rust-IDE not working in Brackets v1.4

### ISSUE THREAD

**Issue by Ajbawa** [rrandom/Brackets-Rust-IDE#2]
Brackets 1.4
- OS: Win 8.1,  64-bit

Exception in 'RustHinter:update' listener on NodeConnection TypeError: Cannot read property '1' of null TypeError: Cannot read property '1' of null
    at file:///C:/Users/abawa/AppData/Roaming/Brackets/extensions/user/rrandom.rust-ide/RustHintProvider.js:114:40
    at Array.map (native)
    at extractHints (file:///C:/Users/abawa/AppData/Roaming/Brackets/extensions/user/rrandom.rust-ide/RustHintProvider.js:113:11)
    at resolveHint (file:///C:/Users/abawa/AppData/Roaming/Brackets/extensions/user/rrandom.rust-ide/RustHintProvider.js:142:26)
    at file:///C:/Users/abawa/AppData/Roaming/Brackets/extensions/user/rrandom.rust-ide/RustHintProvider.js:244:6
    at NodeConnection.trigger (/utils/EventDispatcher.js:222:40)
    at Object.triggerWithArray (/utils/EventDispatcher.js:260:28)
    at NodeConnection._receive (/utils/NodeConnection.js:479:29)

**Comment by rrandom** [comment]
Sorry I have noticed this issue and have fixed it, but I forget to release it.. Now you can update.for the new version

**Comment by Ajbawa** [comment]
Hi,

I will give it a try.
Thanks for the prompt fix.
